import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';
import { format } from 'npm:date-fns@3.6.0';

const fmt = (n) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(n ?? 0);
const fmtPct = (n) => `${(n ?? 0).toFixed(1)}%`;

Deno.serve(async (req) => {
  try {
    if (req.method !== 'POST') {
      return Response.json({ error: 'Method not allowed' }, { status: 405 });
    }

    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await req.json();
    const { recipient_email, share_url, pdf_base64, expires_at } = body;

    if (!recipient_email || !share_url) {
      return Response.json({ error: 'Missing required fields' }, { status: 400 });
    }

    const expiryText = expires_at === 'null' || expires_at === null ? 'Never' : expires_at;
    const todayStr = format(new Date(), 'MMMM d, yyyy');

    const htmlBody = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    body { font-family: Arial, sans-serif; color: #333; line-height: 1.6; }
    .container { max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: #1a3a2a; color: white; padding: 20px; border-radius: 8px; text-align: center; }
    .header h1 { margin: 0; font-size: 24px; }
    .header p { margin: 5px 0 0 0; font-size: 14px; opacity: 0.9; }
    .section { margin: 30px 0; }
    .section h2 { font-size: 16px; font-weight: bold; color: #1a3a2a; border-bottom: 2px solid #ddd; padding-bottom: 10px; }
    .metric-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #f0f0f0; }
    .metric-label { font-weight: 500; }
    .metric-value { text-align: right; }
    .button { display: inline-block; background: #1a3a2a; color: white; padding: 12px 30px; text-decoration: none; border-radius: 6px; margin: 20px 0; font-weight: bold; }
    .footer { text-align: center; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #999; }
    .expiry-note { background: #f9f9f9; padding: 12px; border-left: 4px solid #207d48; margin: 15px 0; font-size: 13px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>Brothers Building</h1>
      <p>Financial Report — ${todayStr}</p>
    </div>

    <p>Hello,</p>
    <p>Your financial report is ready to view. Click the button below to access the full dashboard with interactive charts, detailed breakdowns, and year-to-date metrics.</p>

    <center>
      <a href="${share_url}" class="button">View Full Report</a>
    </center>

    <div class="expiry-note">
      <strong>Expires:</strong> ${expiryText}
    </div>

    <p style="font-size: 13px; color: #666; margin-top: 30px;">
      This report was generated by ${user.full_name || user.email} on ${todayStr}. The PDF attachment contains a snapshot of key metrics and summary sections. For the latest live data, please view the full report using the link above.
    </p>

    <div class="footer">
      <p>&copy; ${new Date().getFullYear()} Brothers Building. All rights reserved.</p>
    </div>
  </div>
</body>
</html>
    `.trim();

    // Send email via Base44 Core integration
    await base44.integrations.Core.SendEmail({
      to: recipient_email,
      subject: `Brothers Building — Financial Report ${todayStr}`,
      body: htmlBody,
      from_name: 'Brothers Building',
    });

    console.log('[INFO] Report email sent to:', recipient_email);

    return Response.json({
      success: true,
      message: `Report emailed to ${recipient_email}`,
    });
  } catch (error) {
    console.error('[ERROR] sendReportEmail:', error.message);
    return Response.json({
      error: error.message,
      stack: error.stack,
    }, { status: 500 });
  }
});